version: "3.9"
services:
  kondo:
    image: kondo:${APP_VERSION}
    depends_on:
      - db
      - redis
    environment: 
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: enabled
      SECRET_KEY_BASE: ${RAILS_SECRET}
      DATABASE_URL: postgres://postgres:${PSQL_PASSWORD}@db/kondo
      REDIS_URL: redis://redis:6793

  db:
    image: postgres:13.4-alpine
    volumes:
      - ${PROD_DIR}/data/psql:/bitnami/postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}

  redis:
    image: redis:6.2.5-alpine
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ${PROD_DIR}/data/redis:/data

  nginx:
    image: kondo-assets:${APP_VERSION}
    restart: always
    depends_on:
      - kondo
    ports:
      - ${PORT}:80
