name: Rails Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          ports:
            - 5432:5432  
          env:
            POSTGRES_PASSWORD: docker
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - name: restore Project Gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: kondo-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          kondo-${{ hashFiles('**/Gemfile.lock') }}
    - uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: Restore Node Modules
      id: npm-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-v14-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-v14-${{ hashFiles('yarn.lock') }}
    - name: npm install
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install
    - name: Build and test with Rake
      env:
        RAILS_ENV: test
      run: |
        # other pre-requisite setup steps...
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        NODE_ENV=test RAILS_ENV=test ./bin/webpack
        bundle exec rake db:create db:migrate
        bundle exec rake test
        ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- \
          --repo ${{ github.repository }} \
          --commit ${{ github.event.pull_request.head.sha || github.sha }} \
          --lcov coverage/lcov/${{github.event.repository.name}}.lcov
