name: Rails Unit Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          ports:
            - 5432:5432  
          env:
            POSTGRES_PASSWORD: docker
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
    - name: restore Project Gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: kondo-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          kondo-${{ hashFiles('**/Gemfile.lock') }}
    - name: Build and test with Rake
      env:
        RAILS_ENV: test
      run: |
        # other pre-requisite setup steps...
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create db:migrate
        bundle exec rake test
        ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- \
          --repo ${{ github.repository }} \
          --commit ${{ github.event.pull_request.head.sha || github.sha }} \
          --lcov coverage/lcov/$repository-name.lcov
